### PR TITLE
fix: image not rounded

### PR DESCRIPTION
**Pull request by krishguptadev**
## Related Issue 

- Information about the related issue 

Closes: # 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |
 
## Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://github.com/web3community/web3community.github.io/blob/main/CODE_OF_CONDUCT.md)

<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/124"></a>

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]

**Review by KukretiShubham — APPROVED** [review]

**Review by mkubdev — APPROVED** [review]
Thanks @krishguptadev

**Comment by KukretiShubham** [comment]
@krishguptadev Your name card don't pop up like others. Maybe fix with another issue 👍🏼

**Comment by krishguptadev** [comment]
> @krishguptadev Your name card don't pop up like others. Maybe fix with another issue 👍🏼 

What do you mean? 😅

**Comment by KukretiShubham** [comment]
> > @krishguptadev Your name card don't pop up like others. Maybe fix with another issue 👍🏼
> 
> What do you mean? sweat_smile

@mkubdev 's card
image

your card 
image

**Comment by krishguptadev** [comment]
> > > @krishguptadev Your name card don't pop up like others. Maybe fix with another issue 👍🏼
> > 
> > What do you mean? sweat_smile
> 
> @mkubdev 's card
> Screenshot from 2021-11-10 15-38-49
> 
> 
> your card 
> image
>  

This looks like a bug.

**Review by shuklaritvik06 — APPROVED** [review]

**Review by Panquesito7 — COMMENTED** [review]
LGTM! 🚀

**Pull request merged**
