### PR TITLE
small letter

### PR DESCRIPTION
**Pull request by PuneetDabral**
## Related Issue 

- Information about the related issue 

Closes: # 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

### CODE REVIEW

**Comment by KukretiShubham** [comment]
I think you didn't understand the issue properly. It says to make text size smaller. Not in smallcase

**Comment by PuneetDabral** [comment]
can i change its css

**Comment by PuneetDabral** [comment]
can you please tell me how small i can change it to 10 px or above...

**Comment by mkubdev** [comment]
You should use [Tailwind](https://tailwindcss.com/docs/font-size)

**Comment by PuneetDabral** [comment]
bro can you help me to do that actually i never use that...

**Comment by KukretiShubham** [comment]
Yes @PuneetDabral you can. But we are using [Talwind](https://tailwindcss.com/docs/font-size). No need to rush, you can take time. Read documentation play with the code. Once you get you it you can create a PR. 
One more thing, please use inclusive language like folks, everyone, people and if you are referring to an individual, use their name.

**Comment by PuneetDabral** [comment]
i am new in github but i will try ...

**Comment by PuneetDabral** [comment]
Screenshot (91)

**Comment by PuneetDabral** [comment]
check any one please check?

**Comment by KukretiShubham** [comment]
Yes, you are on right track. But choose a bit bigger size. Not too small, not too big. Just to fit properly.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please see comments by @KukretiShubham. 🙂

**Comment by PuneetDabral** [comment]
ok bro i will send a pr again after 12 pm

**Comment by Panquesito7** [comment]
> ok bro i will send a pr again after 12 pm

Please do not make multiple pull requests. Instead, implement the needed changes in the same PR. 🙂

**Comment by PuneetDabral** [comment]
ok bro i will update this

**Comment by KukretiShubham** [comment]
@PuneetDabral Kindly use inclusive language , else use the name. 'Bro' 'sir' aren't the inclusive words.

**Comment by KukretiShubham** [comment]
@PuneetDabral can you share related screenshot?

**Review by KukretiShubham — COMMENTED** [review]
@Panquesito7 @shuklaritvik06 @vinzvinci do we need to make small only `A new community` smaller? If Yes.
Then LGTM 🚀

**Comment by shuklaritvik06** [comment]
> @Panquesito7 @shuklaritvik06 @vinzvinci do we need to make small only `A new community` smaller? If Yes.
> Then LGTM 🚀  

Nope all the h1 heading should be a bit smaller in size, @mkubdev  suggested him to just change the text size in xl

**Comment by KukretiShubham** [comment]
Hey @PuneetDabral , There is a merge conflict, you can resolve it. Merge conflict occurs when you try to commit on the same line on which the already in line PR committed. You can simply click on resolve and correct the line/code. After reviewing, I will merge.

**Comment by shuklaritvik06** [comment]
Hey @PuneetDabral , Please add some ss , before we can review

**Comment by PuneetDabral** [comment]
i was already send it on discord 
(can you please help me to solve this conflict)

**Comment by PuneetDabral** [comment]
wait @KukretiShubham i will show you

**Comment by KukretiShubham** [comment]
Click on this resolve conflict button. remove duplicate line and other symbols.
image

**Comment by PuneetDabral** [comment]
Screenshot (92)

**Comment by PuneetDabral** [comment]
Screenshot (93)
i

**Comment by KukretiShubham** [comment]
image
You didn't remove the other line. You can edit your file from here.

**Comment by PuneetDabral** [comment]
i will send a pr again from my main branch

**Comment by KukretiShubham** [comment]
@PuneetDabral make sure you fetch upstream. Your fork should be equal to our main.

**Comment by KukretiShubham** [comment]
I am closing this.

**Pull request closed without merging**
