### PR TITLE
changed content on cards

### PR DESCRIPTION
**Pull request by pranavvdesai**
## Related Issue 

- Changed the content on developer path

Closes: #46 

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Review by KukretiShubham — COMMENTED** [review]
Can you please share the screenshots for the changes you have made?

**Comment by pranavvdesai** [comment]
> Can you please share the screenshots for the changes you have made?

image

**Review by KukretiShubham — COMMENTED** [review]
Why you are deleting this; package-lock.json?

**Comment by pranavvdesai** [comment]
> Why you are deleting this; package-lock.json?

ill look into this

**Pull request closed without merging**
