### PR TITLE
Navbar was covering Page content | Fixed

### PR DESCRIPTION
**Pull request by 0shivamh**
## Related Issue 

- Information about the related issue 
In Mobile View When the user expand the menu, the menu was covering the page content so I have changed the position to navbar to fix it.

Closes: # 

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 CPT2109270058-448x457  | op

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Awesome work! Thanks for your contribution! 🚀

**Review by shuklaritvik06 — COMMENTED** [review]
LGTM

**Review by shuklaritvik06 — APPROVED** [review]

**Review by vinzvinci — APPROVED** [review]
LGTM 👍

**Comment by mkubdev** [comment]
LGTM!

**Pull request merged**
