### PR TITLE
add a emoji in footer

### PR DESCRIPTION
**Pull request by PuneetDabral**
## Related Issue 

- Information about the related issue 

Closes: #24

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]
LGTM 👍

**Review by shuklaritvik06 — APPROVED** [review]
CITY :) Thanks for the contribution! Really appreciate it 😄

**Review by Panquesito7 — APPROVED** [review]
Thanks for your contribution! 😄

**Comment by PuneetDabral** [comment]
if you have any beginner friendly issue feel free to tell me i am new in git hub as well as open source i am in learning face so please give me chance to contribute more and more

**Comment by KukretiShubham** [comment]
Hey, Thanks for the contribution. But, using emoji might break in some browser that have unicode issue (i m not sure). @vinzvinci @shuklaritvik06 @Panquesito7 
Otherwise LGTM 🚀

**Comment by shuklaritvik06** [comment]
> Hey, Thanks for the contribution. But, using emoji might break in some browser that have unicode issue (i m not sure). @vinzvinci @shuklaritvik06 @Panquesito7 
> Otherwise LGTM 🚀

Hmm, maybe &hearts; will work?

**Comment by Panquesito7** [comment]
> > Hey, Thanks for the contribution. But, using emoji might break in some browser that have unicode issue (i m not sure). @vinzvinci @shuklaritvik06 @Panquesito7
> > Otherwise LGTM 🚀
> 
> Hmm, maybe `&hearts;`will work?

Just what I thought on 👍 but I'm not sure if that will work. 🤔

**Comment by shuklaritvik06** [comment]
> > > Hey, Thanks for the contribution. But, using emoji might break in some browser that have unicode issue (i m not sure). @vinzvinci @shuklaritvik06 @Panquesito7
> > > Otherwise LGTM 🚀
> > 
> > Hmm, maybe `&hearts;`will work?
> 
> Just what I thought on 👍 but I'm not sure if that will work. 🤔
> 

We can check that, but I think it'll work 🤔

**Comment by shuklaritvik06** [comment]
> if you have any beginner friendly issue feel free to tell me i am new in git hub as well as open source i am in learning face so please give me chance to contribute more and more

Great to hear @PuneetDabral that you are interested in contributing to Open-source :) . I would suggest you to join our org by raising an issue here - https://github.com/web3community/start-here

You'll get to interact with some awesome folks there :)

**Comment by PuneetDabral** [comment]
ok bro i will ...lets talk in discord

**Pull request merged**
