### PR TITLE
[BUG] Update footer links on mobile

### PR DESCRIPTION
**Pull request by pattimcletchie**
## Related Issue [#70 ](https://github.com/web3community/web3community.github.io/issues/70)

- The footer links had the incorrect class name on them

Closes: #70  

### Describe the changes you've made
The list items under Resources, Legal stuff, and Contact were set to `inline-block` on mobile making them sit inline with each other. I removed that class name and updated the block class name from `md:block` to `block` since we want them to always display as `block`.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have tested this locally on my machine in 3 different browsers and devices.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 
Screen Shot 2021-10-04 at 8 26 10 PM
 | 
Screen Shot 2021-10-04 at 9 28 14 PM
|
 
## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Thanks! 🚀

**Review by shuklaritvik06 — APPROVED** [review]
LGTM 🎉 Thanks @pattimcletchie 😄

**Review by vinzvinci — APPROVED** [review]
LGTM 👍

**Comment by mkubdev** [comment]
Awesome thanks @pattimcletchie 🚀

**Pull request merged**
