### PR TITLE
Add hamburger icon animation

### PR DESCRIPTION
**Pull request by nandan-shah**
## Related Issue 

Closes: #49 

### Describe the changes you've made

added Animation to the Hamburger icon.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I tested the functionality of my changes on the browser by running the project.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
image image | imageimage
 

 
## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Review by shuklaritvik06 — APPROVED** [review]
LGTM 🎉

**Comment by shuklaritvik06** [comment]
Wait for @mkubdev to review this :)

**Review by Panquesito7 — APPROVED** [review]
Awesome work! 🚀

**Review by vinzvinci — APPROVED** [review]
LGTM 👍 

kubdev is busy, so I be taking care this

**Review by mkubdev — COMMENTED** [review]
Nice one 🧨

**Pull request merged**
