### PR TITLE
feat: add URL at button and remove active in navbar

### PR DESCRIPTION
**Pull request by vinzvinci**
## Related Issue 

- Information about the related issue 
N/A

Closes: # 

### Describe the changes you've made
I added URL of start-here repository at button and remove `active` text in navbar and change it to `Home` text.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)
 Original           | Updated
 :--------------------: |:--------------------:
image | !image |

### CODE REVIEW

**Comment by shuklaritvik06** [comment]
Can you share some ss maybe ?

**Comment by vinzvinci** [comment]
> Can you share some ss maybe ?

Added at top section

**Review by shuklaritvik06 — APPROVED** [review]
LGTM :)

**Comment by mkubdev** [comment]
LGTM :)

**Pull request merged**
