### PR TITLE
Removed favicon's background web3community#35

### PR DESCRIPTION
**Pull request by 0shivamh**
## Related Issue 

- Information about the related issue 

Closes: #35 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)
fav

### CODE REVIEW

**Comment by Panquesito7** [comment]
How does it look without the background? Please add a screenshot. 🙂

**Comment by shuklaritvik06** [comment]
> How does it look without the background? Please add a screenshot. slightly_smiling_face

Yes Please add a ss :)

**Comment by 0shivamh** [comment]
> > How does it look without the background? Please add a screenshot. slightly_smiling_face
> 
> Yes Please add a ss :)

please check, the logo is not visible that much

**Comment by Panquesito7** [comment]
What if we convert the text to white instead of being black? 🤔

**Comment by mkubdev** [comment]
> What if we convert the text to white instead of being black? 🤔

Yes i think it's better !

**Comment by shuklaritvik06** [comment]
> > What if we convert the text to white instead of being black? 🤔
> 
> Yes i think it's better ! 

Yes

**Comment by 0shivamh** [comment]
> What if we convert the text to white instead of being black?

that logo is too blurry

**Comment by shuklaritvik06** [comment]
Hey @0shivamh , I am closing this PR as the logo is blurry on removing the background , so we will have a discussion on this . Thnak you for your contribution :)

**Pull request closed without merging**
