### PR TITLE
add moderators-details

### PR DESCRIPTION
**Pull request by shreyaansjain06**
## Related Issue #107 

- Information about the related issue 

Closes: # 

### Describe the changes you've made
Replace lorem with actual details

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
On localhost

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 Screenshot 2021-11-10 at 9 12 44 AM | Screenshot 2021-11-10 at 9 12 28 AM |
 
## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/web3community/web3community.github.io/blob/main/CODE_OF_CONDUCT.md)

<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/123"></a>

### CODE REVIEW

**Review by krishguptadev — APPROVED** [review]

**Comment by mkubdev** [comment]
:(

**Comment by shreyaansjain06** [comment]
I dont know that you are also moderator No problem 
I will add you also just share your bio [here](#107)

**Comment by shreyaansjain06** [comment]
Sorry i forgot to add yours

**Comment by shuklaritvik06** [comment]
Hey @shreyaansjain06 please update the screenshot :)

**Comment by krishguptadev** [comment]
small ques, why aren't all the avatars rounded but just mine.

**Review by mkubdev — APPROVED** [review]
👏

**Review by vinzvinci — APPROVED** [review]
Awesome! Love it!

**Review by shuklaritvik06 — APPROVED** [review]
LGTM 🎉

**Comment by mkubdev** [comment]
> small ques, why aren't all the avatars rounded but just mine.

We should use `rounded-full` from tailwindCSS

**Comment by shuklaritvik06** [comment]
> > small ques, why aren't all the avatars rounded but just mine.
> 
> We should use `rounded-full` from tailwindCSS

+1

**Review by Panquesito7 — COMMENTED** [review]
LGTM! 🚀

**Pull request merged**
