### PR TITLE
 feat: Add Discord social in the footer 

### PR DESCRIPTION
**Pull request by marpit19**
## Related Issue 

- Information about the related issue 
It would be nice if we could add Discord to the list of socials at the bottom.

Closes: # 

### Describe the changes you've made
* Add Discord social in the footer

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)
image

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/web3community/.github/blob/main/CODE_OF_CONDUCT.md)

<a href="https://gitpod.io/#https://github.com/web3community/web3community.github.io/pull/139"></a>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]
Awesome work! 🚀 Thanks!

**Review by krishguptadev — APPROVED** [review]

**Review by vinzvinci — APPROVED** [review]

**Review by shuklaritvik06 — APPROVED** [review]
Looks Good!

**Review by mkubdev — COMMENTED** [review]
Nice work @marpit19 ⭐

**Comment by marpit19** [comment]
> Nice work @marpit19 ⭐

thanks 😄

**Pull request merged**
