### PR TITLE
feat: Add a favicon to the website

### PR DESCRIPTION
**Pull request by Panquesito7**
### Describe the changes you've made

- Add a favicon to the website.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]
LGTM 👍 

Please review @mkubdev

**Review by shuklaritvik06 — APPROVED** [review]
Cool I Trust You!

**Review by rohan-kulkarni-25 — COMMENTED** [review]
Suggest to add tittle just before the head tags end ( Not mandatory but it is helpful )

**Comment by mkubdev** [comment]
LGTM guys

**Pull request merged**
